configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/outreach-isaacR23%2Fpersonatest-7456602a987f7455c3c8d2c956bacf4ff27bee22eeeac2cc19ccba8fbdeacc15.yml
